<?php
// language arrays
if (isset($_REQUEST['language'])) {
	$language = $_REQUEST['language'];
} else {
	$language = 1;
}


// if/else statement to see if english or spanish selected 
if ($language==2) {
	// spanish selected	
	$langtext = array(
		"Find Programs Near You" => "Encuentre Programas Cerca de Usted",
		"Provider Login" => "Ingreso de Proveedores",
		"Powered by NiJeL" => "Sitio desarrollado por <a href=\"http://nijel.org/\" target=\"_blank\">NiJeL</a>",
		"Within" => "Dentro de",
		"miles of" => "millas de",
		"Address" => "Dirección",
		"City" => "Ciudad",
		"State" => "Estado",
		"Zip" => "Código Postal",
		"Language" => "Idioma",
		"Required" => "Obligatorio",
		"Click Here For Advanced Search Options" => "Presione Aquí Para Opciones de Búsqueda Avanzada",
		"Search for programs based on activities available, ages served, or special features, including financial assistance, acceptance of DES Child Care subsidies, availability of summer programs, and other specialized program options." => "Busque programas en base a las actividades que ofrecen, las edades que sirven o características especiales incluyendo asistencia económica, aceptación de subsidios de DES para Cuidado de Niños, disponibilidad de programas de verano y otras opciones de programas especializados.",
		"Advanced Search Options" => "Opciones de Búsqueda Avanzada",
		"To narrow your search results, make one or more selections below. Please note that the information below is not currently available for all programs, but providers are continuing to add and update their directory listings." => "<b>Para limitar los resultados de su búsqueda, seleccione una o más de las opciones siguientes.</b> <i>Tenga en cuenta que la información siguiente aún no está disponible para todos los programas. Sin embargo, los proveedores continúan actualizando su información en el directorio.</i>",
		"Select From School Year or Summer Programs" => "Seleccione Entre Programas Durante el Año Escolar o Programas de Verano",
		"Programs that are open ONLY during the school year" => "Programas abiertos SOLO durante el año escolar",
		"Programs that are open ONLY during the summer" => "Programas abiertos SOLO durante el verano",
		"Programs that are open during BOTH the school year and summer" => "Programas abiertos durante el año escolar y el verano",
		"Select Program Activities" => "Seleccione las Actividades ",
		"Tutoring/Academic Enrichment" => "Tutoría/Enriquecimiento Académico",
		"Arts and Culture" => "Arte y Cultura",
		"Sports and Recreation" => "Deportes y Recreación",
		"Volunteering/Community Service" => "Voluntariado/Servicio Comunitario",
		"Leadership" => "Liderazgo",
		"Character Education" => "Educación del Carácter",
		"Prevention" => "Prevención",
		"Nutrition" => "Nutrición",
		"Mentoring" => "Mentoría",
		"Support Services (medical, dental, mental health, etc.)" => "Servicios Sociales (medicos, dentales, mentales, etc.)",
		"Select Ages Served" => "Seleccione las Edades",
		"Select Special Features" => "Seleccione Características Especiales",
		"No Fee" => "Sin Costo",
		"Financial Assistance Available" => "Disponibilidad de Asistencia Económica",
		"Scholarships Available" => "Disponibilidad de Becas",
		"Accepts DES Child Care Subsidy" => "Aceptan Subsidios de DES para Cuidado de Niños",
		"Transportation Provided" => "Disponibilidad de Transporte",
		"Provides Snacks and/or Meals" => "Ofrecen Refrigerios o Comidas",
		"Spanish-speaking Staff" => "Personal que Habla Español",
		"Other Languages Spoken" => "Personal que Habla Otros Idiomas",
		"Multiple Child Discount Available" => "Disponibilidad de Descuento Para Participantes Múltiples",
		"Search Results" => "Resultados de su Búsqueda",
		"Search Address" => "Dirección de su Búsqueda",
		"Choose Language" => "Elija el idioma",
		"Set" => "Establecer",
		"Search" => "Buscar",
		"You searched for" => "Usted buscó",
		"School Year Programs" => "Programas Durante el Año Escolar",
		"Summer Programs" => "Programas de Verano",
		"Public Transit Directions To Here From" => "Instrucciones de Llegada Aquí Desde",
		"Back to Your Search" => "Regresar a Su Búsqueda",
		"Last Updated" => "Última actualización",
		"Website" => "Página Web",
		"Phone" => "Teléfono",
		"Fax" => "Fax",
		"Email" => "Correo Electrónico",
		"Activities" => "Actividades",
		"Ages Served" => "Edades Servidas",
		"Hours of Operation" => "Horario de Servicio",
		"Morning Start Time" => "Inicio de Horario Matutino",
		"Morning End Time" => "Final de Horario Matutino",
		"Afternoon Start Time" => "Inicio de Horario Vespertino ",
		"Afternoon End Time" => "Fin de Horario Vespertino",
		"Weekend Hours" => "Horario de Fin de Semana",
		"Start Time" => "Hora de Entrada",
		"End Time" => "Hora de Salida",
		"Closed" => "Cerrado",
		"Other Program Information" => "Información Adicional Sobre el Programa",
		"Financial" => "Económica",
		"Transportation/Food" => "Transporte/Comida",
		"Financial assistance available" => "Disponibilidad de asistencia económica",
		"DES assistance accepted" => "Aceptación de asistencia de DES",
		"Scholarship assistance available" => "Disponibilidad de Becas",
		"Multiple child discount available" => "Disponibilidad de Descuento Para Participantes Múltiples",
		"Other financial assistance available" => "Disponibilidad de otros tipos de asistencia económica",
		"Transportation assistance available" => "Disponibilidad de Transporte",
		"Breakfast provided" => "Se ofrece desayuno",
		"Lunch provided" => "Se ofrece almuerzo",
		"Dinner provided" => "Se ofrece cena",
		"Snacks provided" => "Se ofrecen refrigerios",
		"Spanish spoken" => "Se habla español",
		"Other languages spoken" => "Se hablan otros idiomas",
		"Fees assessed on a sliding scale" => "El costo se calcula en base a sus posibilidades de pago",
		"Average monthly transportation cost" => "Costo promedio mensual de transporte",
		"Referrals for needed services provided" => "Se ofrecen referencias para otros servicios",
		"Parent education provided" => "Se ofrece educación para padres de familia",
		"Information and handouts provided to parents" => "Se ofrece informacion para padres de familia",
		"Other items provided to parents" => "Otros servicios prestados a los padres",
		"Program type" => "Tipo de Programa",
		"21st Century Community Center" => "Centro Comunitario 21st Century",
		"Faith-based Program" => "Programa de base religiosa",
		"Public School Based Program" => "Programa de Escuela Pública",
		"Private School Based Program" => "Programa de Escuela Privada",
		"Home Based Program" => "Programa de Casa",
		"Corporate Run Program" => "Programa Administrado Por Empresas",
		"Community Based Program" => "Programa Comunitario",
		"Other" => "Otro",
		"Please enter your 5 digit or 5 digit+4 zip code." => "Por favor, introduzca su 5 dígitos 4 o 5 dígitos del código postal.",
		"Invalid characters in your zip code. Please try again." => "Los caracteres no válidos en su código postal. Por favor, inténtelo de nuevo.",
		"The hyphen character should be used with a properly formatted 5 digit+four zip code, like 12345-6789. Please try again." => "El carácter de guión debe ser utilizado con un formato adecuado 5 dígitos del código postal 4, al igual que 12345-6789. Por favor, inténtelo de nuevo.",
		"Other Options Chosen" => "Otras Opciones Elegidas",
		"No Locations Match Your Search Criteria. Unfortunately, your search returned no matching results. Please go back and pick a new location or select different search criteria. Thank you." => "<h1>No hay ubicaciones que coinciden con su criterio de búsqueda.<h1><p>Desafortunadamente, su búsqueda no produjo resultados coincidentes. Por favor, <a href=\"advancedsearchhome.php?language=2\">volver atrás</a> y elija una nueva ubicación o seleccioné diferentes criterios de búsqueda. Gracias.</p>",
		"Go!" => "Ir!",
		"Not Updated" => "No Se Actualiza",
		"This program charges a fee" => "Este programa cobra una tarifa",
		"Weekly" => "Cada semana",
		"Monthly" => "Cada mes",
		"Quarterly" => "Trimestralmente",
		"Per School Semester" => "Por semestre escolar",
		"Annual" => "Anual",
		"Summer" => "Verano",
		"cost" => "costo",
		"Monday" => "Lunes",
		"Tuesday" => "Martes",
		"Wednesday" => "Miércoles",
		"Thursday" => "Jueves",
		"Friday" => "Viernes",
		"Saturday" => "Sábado",
		"Sunday" => "Domingo",
		"Science, Technology, Engineering, and Mathematics" => "Ciencia, Tecnología, Ingeniería, y Matemáticas",
		"College and Career Readiness" => "Preparación para la Universidad y Una Carrera"



	);

}else{
	// english selected
	$langtext = array(
		"Find Programs Near You" => "Find Programs Near You",
		"Provider Login" => "Provider Login",
		"Powered by NiJeL" => "Powered by <a href=\"http://nijel.org/\" target=\"_blank\">NiJeL</a>",
		"Within" => "Within",
		"miles of" => "miles of",
		"Address" => "Address",
		"City" => "City",
		"State" => "State",
		"Zip" => "Zip",
		"Language" => "Language",
		"Required" => "Required",
		"Click Here For Advanced Search Options" => "Click Here For Advanced Search Options",
		"Search for programs based on activities available, ages served, or special features, including financial assistance, acceptance of DES Child Care subsidies, availability of summer programs, and other specialized program options." => "Search for programs based on activities available, ages served, or special features, including financial assistance, acceptance of DES Child Care subsidies, availability of summer programs, and other specialized program options.",
		"Advanced Search Options" => "Advanced Search Options",
		"To narrow your search results, make one or more selections below. Please note that the information below is not currently available for all programs, but providers are continuing to add and update their directory listings." => "<b>To narrow your search results, make one or more selections below.</b> <i>Please note that the information below is not currently available for all programs, but providers are continuing to add and update their directory listings.</i>",
		"Select From School Year or Summer Programs" => "Select From School Year or Summer Programs",
		"Programs that are open ONLY during the school year" => "Programs that are open ONLY during the school year",
		"Programs that are open ONLY during the summer" => "Programs that are open ONLY during the summer",
		"Programs that are open during BOTH the school year and summer" => "Programs that are open during BOTH the school year and summer",
		"Select Program Activities" => "Select Program Activities",
		"Tutoring/Academic Enrichment" => "Tutoring/Academic Enrichment",
		"Arts and Culture" => "Arts and Culture",
		"Sports and Recreation" => "Sports and Recreation",
		"Volunteering/Community Service" => "Volunteering/Community Service",
		"Leadership" => "Leadership",
		"Character Education" => "Character Education",
		"Prevention" => "Prevention",
		"Nutrition" => "Nutrition",
		"Mentoring" => "Mentoring",
		"Support Services (medical, dental, mental health, etc.)" => "Support Services (medical, dental, mental health, etc.)",
		"Select Ages Served" => "Select Ages Served",
		"Select Special Features" => "Select Special Features",
		"No Fee" => "No Fee",
		"Financial Assistance Available" => "Financial Assistance Available",
		"Scholarships Available" => "Scholarships Available",
		"Accepts DES Child Care Subsidy" => "Accepts DES Child Care Subsidy",
		"Transportation Provided" => "Transportation Provided",
		"Provides Snacks and/or Meals" => "Provides Snacks and/or Meals",
		"Spanish-speaking Staff" => "Spanish-speaking Staff",
		"Other Languages Spoken" => "Other Languages Spoken",
		"Multiple Child Discount Available" => "Multiple Child Discount Available",
		"Search Results" => "Search Results",
		"Search Address" => "Search Address",
		"Choose Language" => "Choose Language",
		"Set" => "Set",
		"Search" => "Search",
		"You searched for" => "You searched for",
		"School Year Programs" => "School Year Programs",
		"Summer Programs" => "Summer Programs",
		"Public Transit Directions To Here From" => "Public Transit Directions To Here From",
		"Back to Your Search" => "Back to Your Search",
		"Last Updated" => "Last Updated",
		"Website" => "Website",
		"Phone" => "Phone",
		"Fax" => "Fax",
		"Email" => "Email",
		"Activities" => "Activities",
		"Ages Served" => "Ages Served",
		"Hours of Operation" => "Hours of Operation",
		"Morning Start Time" => "Morning Start Time",
		"Morning End Time" => "Morning End Time",
		"Afternoon Start Time" => "Afternoon Start Time",
		"Afternoon End Time" => "Afternoon End Time",
		"Weekend Hours" => "Weekend Hours",
		"Start Time" => "Start Time",
		"End Time" => "End Time",
		"Closed" => "Closed",
		"Other Program Information" => "Other Program Information",
		"Financial" => "Financial",
		"Transportation/Food" => "Transportation/Food",
		"Financial assistance available" => "Financial assistance available",
		"DES assistance accepted" => "DES assistance accepted",
		"Scholarship assistance available" => "Scholarship assistance available",
		"Multiple child discount available" => "Multiple child discount available",
		"Other financial assistance available" => "Other financial assistance available",
		"Transportation assistance available" => "Transportation assistance available",
		"Breakfast provided" => "Breakfast provided",
		"Lunch provided" => "Lunch provided",
		"Dinner provided" => "Dinner provided",
		"Snacks provided" => "Snacks provided",
		"Spanish spoken" => "Spanish spoken",
		"Other languages spoken" => "Other languages spoken",
		"Fees assessed on a sliding scale" => "Fees assessed on a sliding scale",
		"Average monthly transportation cost" => "Average monthly transportation cost",
		"Referrals for needed services provided" => "Referrals for needed services provided",
		"Parent education provided" => "Parent education provided",
		"Information and handouts provided to parents" => "Information and handouts provided to parents",
		"Other items provided to parents" => "Other items provided to parents",
		"Program type" => "Program type",
		"21st Century Community Center" => "21st Century Community Center",
		"Faith-based Program" => "Faith-based Program",
		"Public School Based Program" => "Public School Based Program",
		"Private School Based Program" => "Private School Based Program",
		"Home Based Program" => "Home Based Program",
		"Corporate Run Program" => "Corporate Run Program",
		"Community Based Program" => "Community Based Program",
		"Other" => "Other",
		"Please enter your 5 digit or 5 digit+4 zip code." => "Please enter your 5 digit or 5 digit+4 zip code.",
		"Invalid characters in your zip code. Please try again." => "Invalid characters in your zip code. Please try again.",
		"The hyphen character should be used with a properly formatted 5 digit+four zip code, like 12345-6789. Please try again." => "The hyphen character should be used with a properly formatted 5 digit+four zip code, like 12345-6789. Please try again.",
		"Other Options Chosen" => "Other Options Chosen",
		"No Locations Match Your Search Criteria. Unfortunately, your search returned no matching results. Please go back and pick a new location or select different search criteria. Thank you." => "<h1>No Locations Match Your Search Criteria.</h1><p>Unfortunately, your search returned no matching results. Please <a href=\"advancedsearchhome.php\">go back</a> and pick a new location or select different search criteria. Thank you.</p>",
		"Go!" => "Go!",
		"Not Updated" => "Not Updated",
		"This program charges a fee" => "This program charges a fee",
		"Weekly" => "Weekly",
		"Monthly" => "Monthly",
		"Quarterly" => "Quarterly",
		"Per School Semester" => "Per School Semester",
		"Annual" => "Annual",
		"Summer" => "Summer",
		"cost" => "cost",
		"Monday" => "Monday",
		"Tuesday" => "Tuesday",
		"Wednesday" => "Wednesday",
		"Thursday" => "Thursday",
		"Friday" => "Friday",
		"Saturday" => "Saturday",
		"Sunday" => "Sunday",
		"Science, Technology, Engineering, and Mathematics" => "Science, Technology, Engineering, and Mathematics",
		"College and Career Readiness" => "College and Career Readiness"



	);

}
?>

