from django.conf.urls import patterns, include, url
from azcase_admin import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^programs/$', views.sitesUsersLocations, name='programs'),
    url(r'^users/$', views.sitesUsersLocations, name='users'),
    url(r'^locations/$', views.sitesUsersLocations, name='locations'),
    url(r'^filterSites/$', views.filterSites, name='filterSites'),
    url(r'^filterUsers/$', views.filterUsers, name='filterUsers'),
    url(r'^filterLocations/$', views.filterLocations, name='filterLocations'),
    url(r'^addPrograms/$', views.addPrograms, name='addPrograms'),
    url(r'^addUsers/$', views.addUsers, name='addUsers'),
    url(r'^addLocations/$', views.addLocations, name='addLocations'),
    url(r'^downloadData/$', views.downloadData, name='downloadData'),
    url(r'^editPrograms/$', views.editPrograms, name='editPrograms'),
    url(r'^editUsers/$', views.editUsers, name='editUsers'),
    url(r'^editLocations/$', views.editLocations, name='editLocations'),
    url(r'^verifyPrograms/$', views.verifyPrograms, name='verifyPrograms'),
    url(r'^removePrograms/$', views.removePrograms, name='removePrograms'),
    url(r'^removeUsers/$', views.removeUsers, name='removeUsers'),
    url(r'^removeLocations/$', views.removeLocations, name='removeLocations'),
    url(r'^comparePrograms/$', views.comparePrograms, name='comparePrograms'),
    url(r'^compareUsers/$', views.compareUsers, name='compareUsers'),
    url(r'^compareLocations/$', views.compareLocations, name='compareLocations'),
    url(r'^emailUsers/$', views.emailUsers, name='emailUsers'),
    url(r'^emailAllUsers/$', views.emailAllUsers, name='emailAllUsers'),
    url(r'^updateDuplicateRecords/$', views.updateDuplicateRecords, name='updateDuplicateRecords'),
    url(r'^duplicatePrograms/$', views.duplicatePrograms, name='duplicatePrograms'),
    url(r'^duplicateProgram/$', views.duplicateProgram, name='duplicateProgram'),
    url(r'^markNotDuplicateProgram/$', views.markNotDuplicateProgram, name='markNotDuplicateProgram'),
    url(r'^duplicateUsers/$', views.duplicateUsers, name='duplicateUsers'),
    url(r'^duplicateUser/$', views.duplicateUser, name='duplicateUser'),
    url(r'^markNotDuplicateUser/$', views.markNotDuplicateUser, name='markNotDuplicateUser'),
    url(r'^duplicateLocations/$', views.duplicateLocations, name='duplicateLocations'),
    url(r'^duplicateLocation/$', views.duplicateLocation, name='duplicateLocation'),
    url(r'^markNotDuplicateLocation/$', views.markNotDuplicateLocation, name='markNotDuplicateLocation'),
    url(r'^manageUsersData/$', views.manageUsersData, name='manageUsersData'),
    url(r'^customReports/$', views.customReports, name='customReports'),
)
